version: '3.3'
services:
  front:
    build:
      context: ./docker
    environment:
      LOCAL_USER_ID: $UID
    volumes:
      - ".:/project"
      - "~/.ssh:/.host_ssh"
      - ".bash_history:/.bash_history"
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
