version: '3.3'
services:
  front:
    build:
      context: ./docker
    environment:
      LOCAL_USER_ID: $UID
    volumes:
      - ".:/project"
      - "~/.ssh:/.host_ssh"
    stdin_open: true
    tty: true
